[package]
name = "lit-utilities-wasm"
version = "0.1.0"
edition = "2021"
publish = true
description = "Cryptographic utilities used by Lit Protocol network for client side operations"
homepage = "https://github.com/LIT-Protocol/js-sdk"
license = "MIT"
repository = "https://github.com/LIT-Protocol/js-sdk"
[lib]
crate-type = ["cdylib", "rlib"]

[features]

[dependencies]
# wasm and serialization support
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
serde = "1.0"
serde_json = "1.0"
serde_bare = "0.5"
serde_bytes = "0.11.14"
serde-wasm-bindgen = "0.6"

# cryptographic dependencies
blsful = { version = "2.5.7", default-features = false, features = ["rust"] }
curve25519-dalek = { version = "=4.2.2", features = ["rand_core", "group"], package = "curve25519-dalek-ml" }
hd-keys-curves-wasm = { version = "1.0.1", default-features = false, features = ["k256", "p256"] }
lit-frost = { version = "0.1.3", git = "https://github.com/LIT-Protocol/lit-frost" }
ed25519-dalek = "2.1"
ed448-goldilocks = { version = "0.13", package = "ed448-goldilocks-plus" }
frost-core = { version = "1.0.0", features = ["internals"], git = "https://github.com/LIT-Protocol/frost.git" }
frost-ed25519 = { version = "1.0.0", git = "https://github.com/LIT-Protocol/frost.git" }
frost-ed448 = { version = "1.0.0", git = "https://github.com/LIT-Protocol/frost.git" }
frost-p256 = { version = "1.0.0", git = "https://github.com/LIT-Protocol/frost.git" }
frost-p384 = { version = "1.0.0", git = "https://github.com/LIT-Protocol/frost.git" }
frost-redjubjub = { version = "1.0.0", git = "https://github.com/LIT-Protocol/frost.git" }
frost-rerandomized = { version = "1.0.0", git = "https://github.com/LIT-Protocol/frost.git" }
frost-ristretto255 = { version = "1.0.0", git = "https://github.com/LIT-Protocol/frost.git" }
frost-secp256k1 = { version = "1.0.0", git = "https://github.com/LIT-Protocol/frost.git" }
frost-taproot = { version = "1.0.0", git = "https://github.com/LIT-Protocol/frost.git" }

# curve and elliptic-curve cryptography
elliptic-curve = "0.13"
k256 = { version = "0.13", features = ["arithmetic", "schnorr"] }
p256 = { version = "0.13", features = ["arithmetic"] }
p384 = { version = "0.13", features = ["arithmetic"] }
jubjub = { version = "0.10.4", package = "jubjub-plus" }
reddsa = "0.5"
subtle = "2.6"

# hash and encoding utilities
sha2 = "0.10"
hex = "0.4"
base64_light = "0.1"

# random number generation
getrandom = { version = "0.2", features = ["js"] }
rand = "0.8"
rand_core = "0.6"
rand_chacha = "0.3"

# general utilities
anyhow = "1.0"
thiserror = "1.0"
zeroize = "1.8"
vsss-rs = { version = "5.0.0-rc1", features = ["curve25519"] }

# WASM and JS bindings
wasm-bindgen-futures = "0.4.40"
js-sys = "0.3.67"

# SEV (Secure Encrypted Virtualization) support
sev = { version = "2.0.2", default-features = false, features = ["snp", "crypto_nossl"] }

# memory allocation optimization
wee_alloc = { version = "0.4.5", optional = true }

# console debugging and test utilities
console_error_panic_hook = { version = "0.1.7", optional = true }
tsify = { version = "0.4.5", default-features = false, features = ["js"] }

gennaro-dkg = "1.0.0-pre3"


# development dependencies
[dev-dependencies]
wasm-bindgen-test = "0.3.34"
ciborium = "0.2"
group = "0.13"
ff = "0.13"
lazy_static = "1.4"
maplit = "1.0"
rstest = "0.23"
signature_crypto = { version = "2.2", package = "signature" }
