name: CI

on:
  push:
    branches:
      - feature/2614-better-commit-history
  pull_request:
    branches:
      - feature/2614-better-commit-history

jobs:
  bun-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Install dependencies with Bun
        run: bun install

      - name: Run tests with Bun
        env:
          DEBUG: false
        run: bun run ./local-tests/test.ts --network=manzano --version=v0 --filter=testUseValidLitActionCodeGeneratedSessionSigsToPkpSign,testUseEoaSessionSigsToExecuteJsSigningInParallel
