name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - staging/**
      - feat/**
      - feature/**
jobs:
  e2e-connection:
    runs-on: ubuntu-latest-x4-8x
    timeout-minutes: 30
    env:
      NETWORK: cayenne
      DEBUG: true
      MAX_ATTEMPTS: 3
    steps:
      - name: Checkout Lit Actions
        uses: actions/checkout@v4
        id: checkout
        with: 
          fetch-depth: 0
          repository: LIT-Protocol/lit-assets
          token: ${{secrets.GH_PAT}}
          path: lit-assets/
          submodules: false
          sparse-checkout: .
    