name: CI
on:
  push:
    branches:
      - master
      - feature/**
  pull_request:
    branches:
      - master
      - staging/**
      - feat/**
      - feature/**
jobs:
  bun-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Show Bun Version
        run: bun --version

      - name: Install dependencies with Bun
        run: bun install

      - name: Show directory contents
        run: ls -la

      - name: Run tests with Bun
        env:
          DEBUG: false
        run: DEBUG=true yarn test:local --network=manzano --version=v0 --filter=testUseEoaSessionSigsToExecuteJsSigning,testUseEoaSessionSigsToPkpSign,testUsePkpSessionSigsToExecuteJsSigning,testUsePkpSessionSigsToPkpSign
