name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - staging/**
      - feat/**
      - feature/**
jobs:
  master:
    runs-on: ubuntu-latest-x4-8x
    timeout-minutes: 30
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
      - name: Install project dependencies
        run: yarn --frozen-lockfile
      - uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: 'master'
      - name: Build
        run: yarn build:dev
      - name: Run Unit tests
        run: yarn tools --test --unit
  e2e-connection:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      NETWORK: cayenne
      DEBUG: true
      MAX_ATTEMPTS: 3
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Checkout Lit Actions
        uses: actions/checkout@v2
        id: checkout
        with: 
          fetch-depth: 0
          repository: LIT-Protocol/lit-assets
          token: ${{secrets.GH_PAT}}
          path: lit-assets/
          submodules: false
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install project dependencies
        run: yarn install
      - name: Build packages
        id: build
        if: steps.checkout.outputs.exit_code == 0
        run: yarn build:dev
      - name: Run End to End Tests
        if: steps.build.outputs.exit_code == 0
        run: yarn test:local --filter=testUseEoaSessionSigsToExecuteJsSigning,testUseEoaSessionSigsToPkpSign,testUsePkpSessionSigsToExecuteJsSigning,testUsePkpSessionSigsToPkpSign,testUseValidLitActionCodeGeneratedSessionSigsToPkpSign,testUseValidLitActionCodeGeneratedSessionSigsToExecuteJsSigning,testDelegatingCapacityCreditsNFTToAnotherWalletToExecuteJs,testEthAuthSigToEncryptDecryptString,testExecuteJsSignAndCombineEcdsa,testExecutJsDecryptAndCombine,testExecuteJsBroadcastAndCollect  --exclude=Parallel
        