name: CI
on:
  push:
    branches:
      - master
      - feature/**
  pull_request:
    branches:
      - master
      - staging/**
      - feat/**
      - feature/**
jobs:
  nodejs-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install

      - name: Show directory contents
        run: ls -la

      - name: Run tests
        env:
          DEBUG: false
          DELAY_BETWEEN_TESTS: 10000
          NETWORK: manzano
        run: yarn test:local
