name: Testing
on:
  workflow_call:
    outputs:
      unit-tests:
        description: 'unit test results'
        value: ${{jobs.unit-tests.result}}
      intigration-tests:
        description: 'unit test results'
        value: ${{jobs.integration-tests.result}}
  workflow_dispatch: {}

jobs:
  unit-tests:
    runs-on: warp-ubuntu-latest-x64-16x
    timeout-minutes: 10
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: 'master'
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: buildjet/setup-node@v3
        with:
          node-version: 20
          cache: yarn
          cache-dependency-path: ${{ github.workspace }}/yarn.lock
      - name: Install Dependencies
        run: yarn 
      - name: Build
        run: yarn build:dev
      - name: Run Unit tests
        run: yarn test:ci
  integration-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: [unit-tests]
    steps:
      - name: Install Shiva
        uses: ./.github/workflows/use-shiva.yml
        with:
          secrets: inherit
          commit-hash: ae3c20e07eb933b61073689b95f56867c03de252
          main: |
            ehco "test"
          post: |
            docker logs shiva
            docker stop shiva
            docker rm shiva
            docker rmi ghcr.io/lit-protocol/shiva