name: lint
on:
  workflow_call:
    outputs:
      lint_result:
        description: 'lint result'
        value: ${{jobs.linter.result}}

  workflow_dispatch: {}
jobs:
  linter:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
      - name: Install project dependencies
        run: yarn install
      - name: Lint
        run: yarn nx format:check --all
