name: master-trigger
on:
  pull_request:
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  list_changed_files_and_trigger_workflows:
    uses: ./.github/workflows/list-changed-files.yml
    secrets: inherit
  get_shas:
    uses: ./.github/workflows/get-sha.yml
    secrets: inherit
  lint:
    needs: [list_changed_files_and_trigger_workflows]
    uses: ./.github/workflows/lint.yml
    secrets: inherit
  set_network_commit_hashes:
    runs-on: ubuntu-latest
    steps:
    - name: Set commit hashes
      id: commit-hashes
      run: |
        export DATIL_COMMIT_HASH="ae3c20e07eb933b61073689b95f56867c03de252"
        echo "datil_commit_hash=${DATIL_COMMIT_HASH}" >> DATIL_COMMIT_HASH
    outputs:
      datil_commit_hash: ${{steps.commit-hashes.outputs.DATIL_COMMIT_HASH}} 

  unit_tests:
    uses: ./.github/workflows/unit-test.yml
    secrets: inherit
    needs: [lint, get_shas]
  intigration_tests:
      uses: ./.github/workflows/intigration-test.yml
      secrets: inherit
      needs: [lint, get_shas, set_network_commit_hashes]
      with:
        commit: ${{vars.DATIL_COMMIT_HASH}} 
  all_jobs:
    if: ${{ always() }}
    needs: [
      lint,
      unit_tests,
      intigration_tests
    ]
    runs-on: ubuntu-latest
    steps:
      - name: Check status
        run: |
          echo "Linter ${{needs.lint.result}}"
          echo "Tests Unit ${{needs.unit_tests.result}}"
          echo "Tests Intigration"
