name: master-trigger
on:
  pull_request:
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  list_changed_files_and_trigger_workflows:
    uses: ./.github/workflows/list-changed-files.yml
    secrets: inherit
  get_shas:
    uses: ./.github/workflows/get-sha.yml
    secrets: inherit
  lint:
    needs: [list_changed_files_and_trigger_workflows]
    uses: ./.github/workflows/lint.yml
    secrets: inherit
  unit_tests:
    uses: ./.github/workflows/unit-test.yml
    secrets: inherit
    needs: [lint, get_shas]
  intigration_tests:
      uses: ./.github/workflows/intigration-test.yml
      secrets: inherit
      if: ${{needs.list_changed_files_and_trigger_workflows.outputs.lit_core_changed == 'true'}} 
      needs: [lint, get_shas, list_changed_files_and_trigger_workflows, unit_tests]
      with:
        commit: ${{vars.DATIL_COMMIT_HASH}}
  intigration_tests_longrun_epoch:
    uses: ./.github/workflows/intigration-test-long-running.yml
    secrets: inherit
    needs: [lint, get_shas, list_changed_files_and_trigger_workflows, unit_tests]
    with:
      commit: ${{vars.DATIL_COMMIT_HASH}} 
  all_jobs:
    if: ${{ always() }}
    needs: [
      lint,
      unit_tests,
      intigration_tests
    ]
    runs-on: ubuntu-latest
    steps:
      - name: Check status
        run: |
          echo "Linter ${{needs.lint.result}}"
          echo "Tests Unit ${{needs.unit_tests.result}}"
          echo "Tests Intigration"
