name: Unit Testing
on:
  workflow_call:
    outputs:
      unit-tests:
        description: 'unit test results'
        value: ${{jobs.unit-tests.result}}

  workflow_dispatch: {}

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: buildjet/setup-node@v3
        with:
          node-version: 20
          cache: yarn
          cache-dependency-path: ${{ github.workspace }}/yarn.lock
      - name: Check SHA
        uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: 'master'
      - name: Install Dependencies
        run: yarn 
      - name: Build
        run: yarn build:dev
      - name: Run Unit tests
        run: yarn test:unit